import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>giggy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.about}>
          <p>
            Giggy, LLC (GG) are consultants in the sale and sourcing of new and
            used land drilling rigs, new and used mobile drilling rigs, and new
            and used offshore rigs and vessels from the USA, Canada, Europe, and
            Asia. ORN will also help companies buy or sell drilling rig
            equipment and parts, tubular goods, oil and gas production equipment
            and oil field services. ORN can assist companies with their drilling
            rig financing.
            <Link style={{ textDecoration: "underline" }} href={"/about"}>
              [Read More About Us…]
            </Link>
          </p>
          <img src="/home/img0.jpg" alt="home" />
        </div>
        <ul className={styles.sales}>
          <li>
            <h4>Drilling Rigs for Sale</h4>
            <hr />
            <img src="/home/img1.png" alt="" />
            <h2>Drilling Rigs for Sale</h2>
          </li>
          <li>
            <h4>Olifield Equipment and Parts</h4>
            <hr />
            <img src="/home/img2.png" alt="" />
            <h2>Drilling Equipment</h2>
          </li>
          <li>
            <h4>Offshore Rigs & Vessels</h4>
            <hr />
            <img src="/home/img3.jpg" alt="" />
            <h2>Offshore Rigs & Vessels</h2>
          </li>
        </ul>
      </main>
    </>
  );
}
